name: Build and push the release image

on:
    push:
        branches:
            - testing-release

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            # - name: Extract branch name
            #   shell: bash
            #   run: echo "$GITHUB_REF"
            - name: Extract branch name
              shell: bash
              run: ./dev-scripts/build_and_push_release.sh
