name: Build and push the release image

on:
    push:
        branches:
            - testing-release

jobs:
    run-pre-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: sudo mkdir /captain && npm ci && npm run build && npm run tslint && npm run formatter && sudo npm run test
    publish-docker-hub:
        needs: run-pre-checks
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Build and Push Release to DockerHub
              shell: bash
              run: ./dev-scripts/build_and_push_release.sh
